---
abstract: 'Maintain and serve a PGXN web site'
author:
  - 'David E. Wheeler <david.wheeler@pgexperts.com>'
build_requires:
  HTTP::Message::PSGI: 0
  Module::Build: 0.30
  Plack::Test: 0
  Software::License: 0.102340
  Test::File::Contents: 0.20
  Test::MockModule: 0.05
  Test::More: 0.70
  Text::MultiMarkdown: 1.000033
configure_requires:
  Module::Build: 0.30
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PGXN-Site
provides:
  PGXN::Site:
    file: lib/PGXN/Site.pm
    version: v0.10.0
  PGXN::Site::Controller:
    file: lib/PGXN/Site/Controller.pm
    version: v0.10.0
  PGXN::Site::Locale:
    file: lib/PGXN/Site/Locale.pm
    version: v0.10.0
  PGXN::Site::Locale::en:
    file: lib/PGXN/Site/Locale/en.pm
    version: v0.10.0
  PGXN::Site::Locale::fr:
    file: lib/PGXN/Site/Locale/fr.pm
    version: v0.10.0
  PGXN::Site::Router:
    file: lib/PGXN/Site/Router.pm
    version: v0.10.0
  PGXN::Site::Templates:
    file: lib/PGXN/Site/Templates.pm
    version: v0.10.0
requires:
  Carp: 0
  Data::Dump: 1.17
  Email::MIME: 1.901
  Email::Sender::Simple: 0.093110
  Encode: 2.40
  File::Basename: 0
  File::Spec: 0
  Gravatar::URL: 1.02
  HTML::TagCloud: 0.34
  I18N::LangTags::Detect: 1.03
  List::Util: 1.20
  Locale::Maketext: 1.16
  Plack: 0.9956
  Plack::App::File: 0
  Plack::Builder: 0
  Plack::Request: 0.9956
  Plack::Response: 0.9956
  Router::Resource: 0.11
  SemVer: v0.2.0
  Software::License: 0.102340
  Template::Declare: 0.43
  Template::Declare::Tags: 0.43
  WWW::PGXN: v0.12.0
  namespace::autoclean: 0.11
  perl: 5.01
resources:
  bugtracker: http://github.com/theory/pgxn/issues/
  homepage: http://www.pgxn.org/
  license: http://www.opensource.org/licenses/postgresql
  repository: http://github.com/theory/pgxn/tree/
version: v0.10.0
